stages:
  - test
  - build

python-test:
  image: python:3.9-alpine
  stage: test
  before_script:
    - apk add --no-cache g++ make
    - pip install --no-cache-dir -r requirements.txt
    - pip install pytest